In [6]:
'''1. Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions. '''


class Employee:
    employee_count = 0 

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


def input_employee_details():
    name = input("Enter name: ")
    family = input("Enter family: ")
    salary = float(input("Enter salary: "))
    department = input("Enter department: ")
    return name, family, salary, department


employees = []
while True:
    create_employee = input("Do you want to add an employee? (yes/no): ").lower()
    if create_employee != 'yes':
        break
    employees.append(Employee(*input_employee_details()))

fulltime_employees = []
while True:
    create_fulltime_employee = input("Do you want to add a full-time employee? (yes/no): ").lower()
    if create_fulltime_employee != 'yes':
        break
    fulltime_employees.append(FulltimeEmployee(*input_employee_details()))


total_salary = sum(employee.salary for employee in employees) + sum(fulltime_employee.salary for fulltime_employee in fulltime_employees)
average_salary = employees[0].average_salary(total_salary) if employees else 0  
print(f"Total employees: {Employee.employee_count}")
print(f"Average Salary: {average_salary}")


Do you want to add an employee? (yes/no): yes
Enter name: Rakesh
Enter family: yerram
Enter salary: 75000
Enter department: techinacal
Do you want to add an employee? (yes/no): yes
Enter name: anuroop
Enter family: Medhulam
Enter salary: 90000
Enter department: frontend
Do you want to add an employee? (yes/no): no
Do you want to add a full-time employee? (yes/no): yes
Enter name: Sai prakash reddy
Enter family: Sangam
Enter salary: 100000
Enter department: technical
Do you want to add a full-time employee? (yes/no): yes
Enter name: Aniruth
Enter family: kanamm
Enter salary: 95000
Enter department: Backend
Do you want to add a full-time employee? (yes/no): no
Total employees: 4
Average Salary: 90000.0


In [5]:
'''Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop) '''

import numpy as np

random_vector = np.random.uniform(1, 20, 20)

reshaped_array = random_vector.reshape(4, 5)

reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Original Random Vector:")
print(random_vector)
print("\nReshaped Array (4 by 5):")
print(reshaped_array)


Original Random Vector:
[ 6.99840905  9.94263101  0.         13.76708006  2.84444805  4.16358755
  0.          9.53583648 14.30452563  4.82181873 11.94550744  9.1878937
  3.5275318   0.          8.88158451  0.          7.06743077  5.89514506
  8.36272752  4.3150562 ]

Reshaped Array (4 by 5):
[[ 6.99840905  9.94263101  0.         13.76708006  2.84444805]
 [ 4.16358755  0.          9.53583648 14.30452563  4.82181873]
 [11.94550744  9.1878937   3.5275318   0.          8.88158451]
 [ 0.          7.06743077  5.89514506  8.36272752  4.3150562 ]]
